name: CI/CD Backend

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  sistema-ventas-api:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./Back-End
        
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
    # Cache Node Modules
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          
    # Despliegue de la aplicación
      - name: Deploy Backend
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        if: github.event.ref == 'refs/heads/main'
        with:
          server: 161.35.227.182
          username: api
          password: admin123
          protocol: ftps
          port: 21
          local-dir: ./Back-End/build/
          server-dir: ./files/
          log-level: standard
    
